"""add github repository fields

Revision ID: 53cd5cf94ed7
Revises: 58d4fe965e5d
Create Date: 2026-09-01 15:49:19.314447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53cd5cf94ed7'
down_revision: Union[str, Sequence[str], None] = '58d4fe965e5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('github_owner', sa.String(length=100), nullable=True))
    op.add_column('projects', sa.Column('github_repo', sa.String(length=100), nullable=True))
    op.add_column('projects', sa.Column('github_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'github_url')
    op.drop_column('projects', 'github_repo')
    op.drop_column('projects', 'github_owner')
    # ### end Alembic commands ###
