"""Add github_number and github_url to issues

Revision ID: 54d72d725e12
Revises: 09cfaf51c231
Create Date: 2026-10-09 03:12:18.564697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54d72d725e12'
down_revision: Union[str, Sequence[str], None] = '09cfaf51c231'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('github_number', sa.Integer(), nullable=True))
    op.add_column('issues', sa.Column('github_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issues', 'github_url')
    op.drop_column('issues', 'github_number')
    # ### end Alembic commands ###
