"""add cicd github run ids and jobs

Revision ID: 7a40a6601705
Revises: e0d6451bf967
Create Date: 2026-09-03 23:10:24.631562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a40a6601705'
down_revision: Union[str, Sequence[str], None] = 'e0d6451bf967'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cicd_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('cicd_run_id', sa.Integer(), nullable=False),
    sa.Column('github_job_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('conclusion', sa.String(length=50), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cicd_run_id'], ['cicd_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cicd_run_id', 'github_job_id', name='uq_cicd_jobs_run_github_job_id')
    )
    op.add_column('cicd_runs', sa.Column('github_run_id', sa.Integer(), nullable=True))
    op.create_unique_constraint('uq_cicd_runs_project_github_run_id', 'cicd_runs', ['project_id', 'github_run_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_cicd_runs_project_github_run_id', 'cicd_runs', type_='unique')
    op.drop_column('cicd_runs', 'github_run_id')
    op.drop_table('cicd_jobs')
    # ### end Alembic commands ###
