"""add engineering health snapshots

Revision ID: b4b5db9e2e40
Revises: a1f2e3d4c5b6
Create Date: 2026-09-20 15:10:20.480047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4b5db9e2e40'
down_revision: Union[str, Sequence[str], None] = 'a1f2e3d4c5b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('engineering_health_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('issue_health', sa.Float(), nullable=False),
    sa.Column('cicd_reliability', sa.Float(), nullable=False),
    sa.Column('delivery_activity', sa.Float(), nullable=False),
    sa.Column('github_activity', sa.Float(), nullable=False),
    sa.Column('lookback_days', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_engineering_health_snapshots_generated_at'), 'engineering_health_snapshots', ['generated_at'], unique=False)
    op.create_index(op.f('ix_engineering_health_snapshots_project_id'), 'engineering_health_snapshots', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_engineering_health_snapshots_project_id'), table_name='engineering_health_snapshots')
    op.drop_index(op.f('ix_engineering_health_snapshots_generated_at'), table_name='engineering_health_snapshots')
    op.drop_table('engineering_health_snapshots')
    # ### end Alembic commands ###
