"""Add GitHub sync status to projects

Revision ID: c3c72d8db220
Revises: 18345941e0ba
Create Date: 2026-10-04 18:08:02.641564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3c72d8db220'
down_revision: Union[str, Sequence[str], None] = '18345941e0ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('github_sync_status', sa.String(length=50), server_default='NOT_CONNECTED', nullable=False))
    op.add_column('projects', sa.Column('github_last_synced_at', sa.DateTime(), nullable=True))
    op.add_column('projects', sa.Column('github_sync_error', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'github_sync_error')
    op.drop_column('projects', 'github_last_synced_at')
    op.drop_column('projects', 'github_sync_status')
    # ### end Alembic commands ###
